name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  container:
    name: Container
    runs-on: ubuntu-24.04
    container:
      image: rust:1.89-bookworm@sha256:948f9b08a66e7fe01b03a98ef1c7568292e07ec2e4fe90d88c07bb14563c84ff
      options: --user root
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        name: Checkout Code

        with:
          persist-credentials: false

      - run: |
          apt-get update
          apt-get install --yes --no-install-recommends ca-certificates
          rm -rf /var/lib/apt/lists/*
        name: Prepare Container Runtime

      - run: cargo build --release --locked
        name: Build Release Binary
        env:
          CARGO_BUILD_JOBS: 4

      - run: cargo run --release --bin toenctl -- version
        name: Smoke Test Version

  native:
    name: Native (${{ matrix.platform }} ${{ matrix.architecture }})
    strategy:
      matrix:
        include:
          - os: macos-15-intel
            platform: macOS 15
            architecture: x86-64
          - os: windows-2025
            platform: Windows 2025
            architecture: x86-64
          - os: windows-11-arm
            platform: Windows 11
            architecture: ARM64
          - os: ubuntu-24.04
            platform: Ubuntu 24.04
            architecture: x86-64
          - os: ubuntu-24.04-arm
            platform: Ubuntu 24.04
            architecture: ARM64
          - os: macos-15
            platform: macOS 15
            architecture: ARM64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        name: Checkout Code

        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@1d1eb14921d9c2d8ea575663e5fe3a0b57868a05 # 1.89
        name: Install Rust Toolchain

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        name: Cache Cargo

      - run: cargo build --release --locked
        name: Build Release Binary
        env:
          CARGO_BUILD_JOBS: 4

      - run: cargo run --release --bin toenctl -- version
        name: Smoke Test Version
