name: Container

on:
  workflow_call:

permissions:
  contents: read

jobs:
  container:
    name: Container
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        name: Checkout Code

        with:
          persist-credentials: false

      - run: make -f Makefile.container verify CONTAINER_IMAGE=toen-ci:${{ github.sha }}
        name: Run Verification In Container
