name: Main

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: main-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml

  container:
    name: Container
    needs: verify
    uses: ./.github/workflows/container.yml

  test:
    name: Test
    needs: verify
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    needs: verify
    uses: ./.github/workflows/build.yml

  security:
    name: Security
    uses: ./.github/workflows/security.yml

  static:
    name: Static
    uses: ./.github/workflows/static.yml
